### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by BadWolf1023** [camelwater/Table-BOT#9]
Heyo! My name is Bad Wolf. I made MKW Table Bot back in 2020 and added features on a somewhat regular basis over the past year and a half, and released the code a few months ago in hopes that people might build on it or contribute. I was given a link to this repo today and was quite excited to see that someone _has_ built on MKW Table Bot in a place that I wasn't aware of. Your code looks well done, great work!

It looks like you added a few nice features, like automated ?wp and ?redo. I haven't fully checked all the features you added, but it looks like you have great ideas. If you are open to it, I am open to adding some of those features to MKW Table Bot. Some won't be added, like automated ?wp, as this would affectively dos attack wiimmfi.de during high usage, but other features like ?redo would be a nice addition! (I think the benefit here is that MKW Table Bot has one set of features, you have a different set of features, and it'd be nice if all the best features were in one place for the MKW community to use.)

I'm also reaching out because you've done an excellent refactor (or rewrite) here, like sqlite for server settings. Would you be interested in _contributing_ to the MKW Table Bot repository? ForestMKW and I just collaborated nicely where he rewrote a new tag AI, and I wrote a shell to compare AIs, and we seamlessly swapped his AI in.

Anyway, just let me know! Thanks! :)

**Comment by camelwater** [comment]
Hey BadWolf! 
I've been a huge fan of your Table Bot Discord bot for a while, so it's great that you've seen my implementation. I didn't realize that you left an issue here, since I've been sort of not active on this project ever since the DDoS on Wiimmfi, but to answer your question, yes, I am open to contribute to your repository. I'll look for any issues that you have and do what I can.
